version: "3.10"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: SaJmGdmrJAeb2nGoHTwG
      POSTGRES_USER: postgres
      POSTGRES_DB: railway
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  data:
